# 🐍 Используем официальный Python-образ
FROM python:3.11-slim

# 📁 Устанавливаем рабочую директорию
WORKDIR /app

# 🧾 Копируем файлы проекта
COPY . .

# 📦 Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# 🚀 Запускаем бот
CMD ["python", "main.py"]
